services:
  questdb:
    image: questdb/questdb:latest
    ports:
      - "9000:9000"
    networks:
      radicle-natives:
        ipv4_address: 10.0.0.2
  radicle-natives:
    build: .
    ports:
      - "8000:8000"
    healthcheck:
      test: curl --fail http://localhost:8000/_health || exit 1
      interval: 30s
      retries: 3
      start_period: 15s
      timeout: 1s
    networks:
      radicle-natives:
        ipv4_address: 10.0.0.1

networks:
  radicle-natives:
    driver: bridge
    ipam:
        config:
            - subnet: 10.0.0.0/24
              gateway: 10.0.0.254