services:
  radicle-natives:
    build: .
    ports:
      - "8000:8000"   # Application Port
    networks:
      radicle-natives:
        ipv4_address: 10.0.0.1
  surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - "8001:8000"   # SurrealDB HTTP/WebSocket API
    entrypoint:
      - /surreal
      - start
      - --user
      - root
      - --pass
      - root
    networks:
      radicle-natives:
        ipv4_address: 10.0.0.2

networks:
  radicle-natives:
    driver: bridge
    ipam:
        config:
            - subnet: 10.0.0.0/24
              gateway: 10.0.0.254