name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "2.2.1"

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run linter
        run: poetry run ruff check .

      - name: Run tests
        run: poetry run pytest --cov=main --cov-report=term-missing --cov-fail-under=99

